openapi: 3.0.0
info:
  title: Project API
  version: 1.0.0
paths:
  /api/projects:
    get:
      summary: List all projects
      operationId: listProjects
      responses:
        '200':
          description: A list of projects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
components:
  schemas:
    Project:
      type: object
      required:
        - id
        - name
        - status
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        code:
          type: string
        status:
          type: string
          enum: [active, archived, pending]
