// Default Consultant Disciplines (37 total)
export const CONSULTANT_DISCIPLINES = [
  { name: 'Access', order: 1 },
  { name: 'Acoustic', order: 2 },
  { name: 'Arborist', order: 3 },
  { name: 'Architect', order: 4 },
  { name: 'ASP3', order: 5 },
  { name: 'BASIX', order: 6 },
  { name: 'Building Code Advice', order: 7 },
  { name: 'Bushfire', order: 8 },
  { name: 'Building Certifier', order: 9 },
  { name: 'Civil', order: 10 },
  { name: 'Cost Planning', order: 11 },
  { name: 'Ecology', order: 12 },
  { name: 'Electrical', order: 13 },
  { name: 'ESD', order: 14 },
  { name: 'Facade', order: 15 },
  { name: 'Fire Engineering', order: 16 },
  { name: 'Fire Services', order: 17 },
  { name: 'Flood', order: 18 },
  { name: 'Geotech', order: 19 },
  { name: 'Hazmat', order: 20 },
  { name: 'Hydraulic', order: 21 },
  { name: 'Interior', order: 22 },
  { name: 'Landscape', order: 23 },
  { name: 'Mechanical', order: 24 },
  { name: 'NBN', order: 25 },
  { name: 'Passive Fire', order: 26 },
  { name: 'Project Manager', order: 27 },
  { name: 'Roof Access', order: 28 },
  { name: 'Site Investigation', order: 29 },
  { name: 'Stormwater', order: 30 },
  { name: 'Structural', order: 31 },
  { name: 'Survey', order: 32 },
  { name: 'Traffic', order: 33 },
  { name: 'Vertical Transport', order: 34 },
  { name: 'Waste Management', order: 35 },
  { name: 'Wastewater', order: 36 },
  { name: 'Waterproofing', order: 37 },
  { name: 'BMS', order: 38 },
  { name: 'ICT', order: 39 },
  { name: 'Lighting', order: 40 },
  { name: 'Security', order: 41 },
  { name: 'Town Planning', order: 42 },
  { name: 'Wind', order: 43 },
] as const;

// Default Contractor Trades (35 total)
export const CONTRACTOR_TRADES = [
  { name: 'Concrete Finisher', order: 1 },
  { name: 'Steel Fixer', order: 2 },
  { name: 'Scaffolder', order: 3 },
  { name: 'Carpenter', order: 4 },
  { name: 'Bricklayer', order: 5 },
  { name: 'Roofer', order: 6 },
  { name: 'Glazier', order: 7 },
  { name: 'Waterproofer', order: 8 },
  { name: 'Plumber', order: 9 },
  { name: 'Electrician', order: 10 },
  { name: 'HVAC Technician', order: 11 },
  { name: 'Insulation Installer', order: 12 },
  { name: 'Drywaller', order: 13 },
  { name: 'Plasterer', order: 14 },
  { name: 'Tiler', order: 15 },
  { name: 'Flooring Installer', order: 16 },
  { name: 'Painter', order: 17 },
  { name: 'Cabinetmaker', order: 18 },
  { name: 'Mason', order: 19 },
  { name: 'Welder', order: 20 },
  { name: 'Landscaper', order: 21 },
  { name: 'Civil', order: 22 },
  { name: 'Concrete', order: 23 },
  { name: 'Demolition', order: 24 },
  { name: 'Excavation', order: 25 },
  { name: 'Facade', order: 26 },
  { name: 'Fire Services', order: 27 },
  { name: 'Formwork', order: 28 },
  { name: 'Hydraulic', order: 29 },
  { name: 'Joinery', order: 30 },
  { name: 'Lift', order: 31 },
  { name: 'Mechanical', order: 32 },
  { name: 'Piling', order: 33 },
  { name: 'Signage', order: 34 },
  { name: 'Structural Steel', order: 35 },
  { name: 'Ceilings', order: 36 },
  { name: 'Electrical', order: 37 },
  { name: 'Fitout', order: 38 },
  { name: 'Flooring', order: 39 },
  { name: 'Glazing', order: 40 },
  { name: 'Landscaping', order: 41 },
  { name: 'Painting', order: 42 },
  { name: 'Precast', order: 43 },
  { name: 'Roofing', order: 44 },
  { name: 'Waterproofing', order: 45 },
] as const;

// Status types for both consultants and contractors
export const STATUS_TYPES = ['brief', 'tender', 'rec', 'award'] as const;

export type ConsultantDisciplineName = typeof CONSULTANT_DISCIPLINES[number]['name'];
export type ContractorTradeName = typeof CONTRACTOR_TRADES[number]['name'];
export type StatusType = typeof STATUS_TYPES[number];
